version: 2.1

jobs:
  lint:
    docker:
      - image: python
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # This key is used if no exact match is found in caches
            - v1-dependencies-
      - run:
          name: Install Dependencies and Lint
          command: |
            pip install -r requirements.txt
            black . --check --diff
      - save_cache:
          key: v1-dependencies-{{ checksum "requirements.txt" }}
          paths:
            - ~/.cache/pip

  test:
    docker:
      - image: python
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # This key is used if no exact match is found in caches
            - v1-dependencies-
      - run:
          name: Install Dependencies and Run Tests
          command: |
            pip install -r requirements.txt
            pytest
      - save_cache:
          key: v1-dependencies-{{ checksum "requirements.txt" }}
          paths:
            - ~/.cache/pip

  publish_docker_image_to_aws:
    docker:
      - image: python
    steps:
      - checkout
      - run:
          name: Publishing docker image to aws ECR
          command: |
            pip install awscli
            docker build --platform linux/amd64 --progress plain -t final-project-college:${CI_COMMIT_SHORT_SHA} .
            aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.eu-west-1.amazonaws.com
            docker tag final-project-college:${CI_COMMIT_SHORT_SHA} ${AWS_ACCOUNT_ID}.dkr.ecr.eu-west-1.amazonaws.com/final-project-college:${CI_COMMIT_SHORT_SHA}
            docker push ${AWS_ACCOUNT_ID}.ecr.eu-west-1.amazonaws.com/final-project-college:${CI_COMMIT_SHORT_SHA}

workflows:
  version: 2
  build-and-test:
    jobs:
      - lint
      - test:
          requires:
            - lint
      - publish_docker_image_to_aws:
          requires:
            - test
