version: 2.1  # Specify CircleCI configuration file format version

jobs:
  build-and-test:  # Job name (can be anything descriptive)
    docker:
      - image: circleci/python:3.x  # Use a pre-built Python image (adjust version if needed)

    steps:
      - checkout  # Checkout the code from the repository

      - restore_cache:  # Restore cache for dependencies (optional, improves performance)
          keys:
            - v1-dependencies-{{ .version }}  # Cache key based on Python version
          paths:
            - ~/.cache/pip

      - run: pip install -r requirements.txt  # Install dependencies

      - save_cache:  # Save cache for dependencies (optional)
          paths:
            - ~/.cache/pip
          key: v1-dependencies-{{ .version }}  # Same cache key

      - run: black . --check --diff  # Run Black code formatter

      - run: pytest . # Run tests using pytest
