version: 2.1

jobs:
  build:
    docker:
      - image: python
    steps:
      - checkout
      - run:
          name: Build Docker Image
          command: docker build --platform linux/amd64 --progress plain . -t projetofinal

  lint:
    docker:
      - image: python
    steps:
      - checkout
      - run:
          name: Install Dependencies and Lint
          command: |
            docker run --rm -v $(pwd):/workdir -w /workdir projetofinal /bin/bash -c "make lint"

  test:
    docker:
      - image: python
    steps:
      - checkout
      - run:
          name: Install Dependencies and Run Tests
          command: |
            docker run --rm -v $(pwd):/workdir -w /workdir projetofinal /bin/bash -c "make test"

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - lint:
          requires:
            - build
      - test:
          requires:
            - build
