version: 2.1

jobs:
  lint:
    docker:
      - image: python
    steps:
      - checkout
      - run:
          name: Install Dependencies and Lint
          command: |
            pip install -r requirements.txt
            black . --check --diff
  test:
    docker:
      - image: python
    steps:
      - checkout
      - run:
          name: Install Dependencies and Run Tests
          command: |
            pytest

workflows:
  version: 2
  build-and-test:
    jobs:
      - lint
      - test:
          requires:
            - lint
